version: '3.8'

services:
  monitor-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
    networks:
      - cloudpulse-network

networks:
  cloudpulse-network:
    driver: bridge 